### ISSUE TITLE
RuntimeError: implement_array_function method already has a docstring when using Embuary

### ISSUE THREAD

**Issue by dustinwilson** [sualfred/script.embuary.helper#28]
I am using Kodi Leia on Manjaro Linux and am getting a series of errors that pop up every time I pretty much do anything with Embuary.

```
2019-11-16 18:30:08.528 T:139947885459200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/dw/.kodi/addons/script.embuary.helper/plugin.py", line 16, in <module>
                                                from resources.lib.plugin_content import *
                                              File "/home/dw/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                from resources.lib.image import *
                                              File "/home/dw/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                from PIL import ImageFilter,Image,ImageOps
                                              File "/usr/lib/python2.7/site-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/site-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
```

Here is a list of python-related packages I have:

```python 3.7.4-2
python-anytree 2.7.2-1
python-appdirs 1.4.3-2
python-asn1crypto 1.2.0-1
python-beaker 1.11.0-1
python-beautifulsoup4 4.8.0-1
python-cachecontrol 0.12.5-4
python-cairo 1.18.2-1
python-cffi 1.13.0-1
python-chardet 3.0.4-2
python-colorama 0.4.1-1
python-cryptography 2.7-1
python-dbus 1.2.10-1
python-dbus-common 1.2.10-1
python-distlib 0.2.9-1
python-distro 1.4.0-1
python-distutils-extra 2.39-3
python-docopt 0.6.2-5
python-gobject 3.34.0-1
python-html5lib 1.0.1-3
python-i3ipc 2.1.1-1
python-idna 2.8-1
python-importlib-metadata 0.23-1
python-jeepney 0.4.1-1
python-keyutils 0.6-2
python-levenshtein 0.12.0-6
python-lockfile 0.12.2-4
python-lxml 4.4.1-1
python-mako 1.0.14-1
python-markdown 3.1.1-2
python-markupsafe 1.1.1-1
python-more-itertools 7.2.0-1
python-msgpack 0.6.2-1
python-npyscreen 4.10.5-2
python-numpy 1.17.3-1
python-packaging 19.2-2
python-pep517 0.6.0-1
python-pexpect 4.7.0-1
python-pillow 6.2.0-1
python-pip 19.2.3-1.5
python-ply 3.11-2
python-progress 1.5-1
python-psutil 5.6.3-1
python-ptyprocess 0.6.0-2
python-pycparser 2.19-1
python-pygments 2.4.2-1
python-pyinotify 0.9.6-4
python-pylast 3.1.0-1
python-pyparsing 2.4.4-1
python-pytoml 0.1.21-1
python-pyudev 0.21.0-6
python-requests 2.22.0-1
python-retrying 1.3.3-4
python-secretstorage 3.1.1-1
python-setuptools 1:41.2.0-1
python-six 1.12.0-1
python-soupsieve 1.9.5-1
python-urllib3 1.25.6-1
python-webencodings 0.5.1-2
python-websocket-client 0.56.0-1
python-xdg 0.26-2
python-xlib 0.25-1
python-yaml 5.1.2-1
python-zipp 0.6.0-1
python2 2.7.17-1
python2-cairo 1.18.2-1
python2-dbus 1.2.10-1
python2-gobject 3.34.0-1
python2-gobject2 2.28.7-2
python2-numpy 1.16.4-2
python2-pillow 6.2.0-1
python2-pycryptodomex 3.9.0-1
python2-simplejson 3.16.1-1
python2-wxpython3 3.0.2.0-2
```

There seems to be an [open issue on numpy for the exception](https://github.com/numpy/numpy/issues/14384).

**Comment by dustinwilson** [comment]
Sorry, should have mentioned that I was using the latest version of Embruary (including this helper) from your repository.

**Comment by sualfred** [comment]
Kodi is sharing the python modules with the one of the OS.
It's caused by a incomptible Pillow package on your system. You have to get rid of it by yourself.

I would try to uninstall/update the pillow package or try different versions.

**Comment by dustinwilson** [comment]
Using the one straight from numpy's repo yields the same results as the one provided by Arch's repo. Mutpy were [having the same problem](https://github.com/mutpy/mutpy/issues/52) with newer versions of numpy, too; they've [seem to have found a workaround](https://github.com/mutpy/mutpy/pull/53) maybe. I've also tried this on Ubuntu and macOS, and if I use any version of numpy higher than 1.15.4 I get these exact errors.

I'm sure there's nothing you can do about it, but leaving this here for others to find.

**Comment by sualfred** [comment]
@dustinwilson 
Just found some minutes to read thru your links. Is it resolved with the newest numpy package?

**Comment by dustinwilson** [comment]
Sorry about the delay. I was away from home. No, the newest numpy package doesn't resolve it.

**Comment by sualfred** [comment]
Ok. Anyway, at least not a issue on my end. But let me know when you can solve it so other users can benefit.

**Comment by dustinwilson** [comment]
Doubtful I'll find a solution unless the numpy people fix it themselves. Mutpy found some workaround, but I'm not proficient enough with python to make sense of what they did. For the moment I'm just preventing upgrading to the latest numpy package to keep things working.

**Comment by sahilx13** [comment]
I created a file name copy.py in my code repository which led to this error, removing the file made it alright. Maybe this is linked to the same problem.
